### ISSUE TITLE
README link broken

### ISSUE THREAD

**Issue by joe-segal** [ryooan/metaculus-bot-forecaster#1]
In the README, in the first line, the link to "AI Benchmarking Competition" is broken.

"This repository is used to use a Github actions to automate the periodic execution of a Google colab notebook that makes LLM-powered forecasts in Metaculus' [AI benchmarking competition](https://www.metaculus.com/project/ai-benchmarking-pilot/)."

**Comment by ryooan** [comment]
Thank you, I've updated the link now.
