### ISSUE TITLE
README secrets screenshot

### ISSUE THREAD

**Issue by joe-segal** [ryooan/metaculus-bot-forecaster#2]
The README secrets screenshot in "Step Four: Set Your Secrets" includes QUESTIONS_API_KEY, which now seems to be deprecated.

https://github.com/ryooan/metaculus-bot-forecaster?tab=readme-ov-file#step-four-set-your-secrets

**Comment by ryooan** [comment]
Thank you, I've updated the readme to add a note before the image that QUESTIONS_API_KEY is no longer needed.
